---
cluster_identifier: "neptune-cluster-demo"
engine: "neptune"
backup_retention_period: 5
preferred_backup_window: "07:00-09:00"
skip_final_snapshot: true
iam_database_authentication_enabled: true
apply_immediately: true
vpc_name_tag: "TEST"
sub_tag: "Public"
